/**
 * User mutations types
 */
export default {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST'
  , FETCH_USER_SUCCESS: 'FETCH_USER'
  , FETCH_USER_FAIL: 'FETCH_USER_FAIL'

  , FETCH_NEWS_REQUEST: 'FETCH_NEWS_REQUEST'
  , FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS'
  , FETCH_NEWS_FAIL: 'FETCH_NEWS_FAIL'
};